import Head from 'next/head'
import styles from './style.module.scss'

import Navbar from '../components/navbar'
import Header from '../components/header'
import About from '../components/about'
import Services from '../components/services'
import Contact from '../components/contact'
import Footer from '../components/footer'

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={''}>
        <Navbar />
        <Header />
        <About />
        <Services />
        <Contact />
      </main>

      <Footer />
    </div>
  )
}
